ClarkCodingChallenge/Models/ApplicationDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace ClarkCodingChallenge.Models
{
    public class ApplicationDBContext : DbContext
    {

        public ApplicationDBContext() { }
        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
            : base(options)
        {

        }

        public DbSet<Contact> Contacts { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }
}

ClarkCodingChallenge/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClarkCodingChallenge.Models
{
    public class Contact
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Required(ErrorMessage = "First Name Required")]
        [Display(Name = "First Name")]
        public string FirstName{ get; set; }

        [Required(ErrorMessage = "Last Name Required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "E-Mail Required")]
        [Display(Name = "E-Mail")]
        [EmailAddress(ErrorMessage = "Please enter a valid E-mail")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Please enter a valid E-mail")]
        public string Email { get; set; }
    }
}

ClarkCodingChallenge/Models/ErrorViewModel.cs
namespace ClarkCodingChallenge.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClarkCodingChallenge/Controllers/ContactsController.cs
using System.Diagnostics;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ClarkCodingChallenge.Models;
using ClarkCodingChallenge.BusinessLogic;

namespace ClarkCodingChallenge.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDBContext _context;
        private ContactsService _contactsService;

        public ContactsController(ApplicationDBContext context, ContactsService contactsService)
        {
            _context = context;
            _contactsService = contactsService;

        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid)
            {
                string dbResult = _contactsService.NewContact(contact.FirstName, contact.LastName, contact.Email);
                if (dbResult == "Success")
                {
                    return View("Confirmation");
                }
                else
                {
                    ViewBag.ErrorMsg = dbResult;
                }

                return Index();
            }
            return View(contact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ContactList(string LastName, bool Desc)
        {
            List<Contact> contacts;
            string lastNameTrimmed = LastName == null? "": LastName.Trim();

            contacts = _contactsService.GetContacts(lastNameTrimmed, Desc);

            return View(contacts);

        }

        [HttpGet]
        public IActionResult ContactList()
        {
            return ContactList("", false);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClarkCodingChallenge/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClarkCodingChallenge.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClarkCodingChallenge/Views/Contacts/Confirmation.cshtml
@{ ViewData["Title"] = "Confirmation Page"; }
<script type="text/javascript">
    var seconds = 10;

    function countdown() {
        seconds = seconds - 1;
        if (seconds < 0) {
            window.location = '@Url.Action("Index", "Contacts")';
        } else {
            document.getElementById("countdown").innerHTML = seconds;
            document.getElementById("countdown2").innerHTML = seconds;
            window.setTimeout("countdown()", 1000);
        }
    }

    window.setTimeout("countdown()", 1000);
</script>


<div class="row">
    <div class="col-md-8">
        <p>New Contact has been added to mailing list successfully. Page will redirect after <span id="countdown">10</span> seconds...</p>
        <br />
        <p>If page doesn't redirect after <span id="countdown2">10</span> seconds click  @Html.ActionLink("Here","Index", "Contacts")</p>
    </div>
</div>

ClarkCodingChallenge/Views/Contacts/ContactList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Contacts List";
}
@model IEnumerable<Contact>

<div class="text-center">
    <h2 class="display-5">E-mail List Contacts</h2>
    <label>@ViewBag.ErrorMsg</label>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @*<a asp-action="EditContact" asp-route-id="@item.id">Edit</a> @Html.Raw("|");*@
                        <a asp-action="DeleteContact" asp-route-id="@item.id">Delete</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <label>There are no Contacts currently Stored. Add a new Contact to View.</label>
        }
    </tbody>
</table>

ClarkCodingChallenge/Views/Contacts/Index.cshtml
@{ ViewData["Title"] = "Contacts Page"; }
@model Contact

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <br />
    <h2 class="display-5">Please enter First Name, Last Name, and Email</h2>
    <br />
    <label>@ViewBag.ErrorMsg</label>
</div>


<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-vertical">
                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" value="Save" class="btn btn-default">Submit</button>
                </div>
            </div>
        }
        </div>
</div>

ClarkCodingChallenge/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Welcome to the Challenge!</h1>

ClarkCodingChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClarkCodingChallenge</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clark Coding Challenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("ContactList","Contacts")">Mail List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Clark Coding Challenge
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>